# Generated by Django 2.2.6 on 2019-10-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0003_auto_20191012_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='text',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/pdfs/'),
        ),
    ]
