# Generated by Django 2.2.6 on 2019-10-13 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acad', '0004_auto_20191013_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Resource',
        ),
    ]
