# Generated by Django 2.2.6 on 2019-10-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0005_auto_20191013_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='resource/pdfs/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='pdf',
            field=models.FileField(upload_to='resource/pdfs/'),
        ),
    ]
