# Generated by Django 2.1.4 on 2019-10-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0006_auto_20191013_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
